.PHONY: clean All

All:
	@echo "----------Building project:[ NoughtsCrossesGame - Debug ]----------"
	@cd "NoughtsCrossesGame" && "$(MAKE)" -f  "NoughtsCrossesGame.mk"
clean:
	@echo "----------Cleaning project:[ NoughtsCrossesGame - Debug ]----------"
	@cd "NoughtsCrossesGame" && "$(MAKE)" -f  "NoughtsCrossesGame.mk" clean
